name: widget_modifier
description: A collection of built-in flutter widget modifiers, which flatten the widget tree and make it easier to read
version: 0.0.2
repository: https://github.com/definev/widget_modifier/tree/main/packages/widget_modifier
issue_tracker: https://github.com/definev/widget_modifier/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
